version: '3.3'

services:
  database:
    container_name: database
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: scout-database
      MYSQL_USER: light
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php

    build:
      context: ./php
    ports:
      - '8523:8032'
    volumes:
      - ./app:/var/www/scout-database
      - ./localpath/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - database
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/scout-database
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database