version: '3.3'

services:
  mailer:
    image: tvial/docker-mailserver
    container_name: mailer
    hostname: mail
    domainname: app.dev
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail/spamassassin:/tmp/spamassassin/
      - ./mail/postfix:/tmp/postfix/
  database:
    container_name: database_c
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: scout-database
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./db:/var/lib/db
  php:
    image: php:8.0-fpm
    container_name: php_c
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/scout-database
  nginx:
    container_name: nginx_c
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/scout-database
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf