
index:
  path: /
  controller: App\Controller\single\MainController::index
  methods: GET

#---------------------------DEBUG---------------------------#

_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

#---------------------------USER---------------------------#

user:
  path: /user/{id}
  controller: App\Controller\user\UserController::show
  requirements:
    id: '\d+'

user.create:
  path: /user/create
  controller: App\Controller\user\UserController::create

user.edit:
  path: /user/{id}/edit
  controller: App\Controller\user\UserController::edit
  requirements:
    id: '\d+'

user.list:
    path: /user/list/{role}
    defaults: { role: all }
    controller: App\Controller\user\UserController::list

user.promote.wolvies:
    path: /user/promote/wolviews/{id}
    controller: App\Controller\user\UserController::promoteWolvies
    requirements:
      id: '\d+'

#---------------------------STRUCTS---------------------------#

struct:
  path: /struct/{id}
  controller: App\Controller\struct\StructController::show
  requirements:
    id: '\d+'

struct.create:
  path: /struct/create
  controller: App\Controller\struct\StructController::create

struct.edit:
  path: /struct/{id}/edit
  controller: App\Controller\struct\StructController::edit
  requirements:
    id: '\d+'

struct.list:
  path: /struct/list/{type}
  defaults: { type: all }
  controller: App\Controller\struct\StructController::list

#---------------------------SHOP---------------------------#

shop:
  path: /shop
  controller: App\Controller\DefaultController::index

#---------------------------EVENTS---------------------------#

events:
  path: /events
  controller: App\Controller\DefaultController::index