
index:
  path: /
  controller: App\Controller\Single\MainController::index
  methods: GET

#---------------------------DEBUG---------------------------#

_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

#---------------------------USER---------------------------#

user:
  path: /user/{id}
  controller: App\Controller\User\ShowUserController
  requirements:
    id: '\d+'

user.create:
  path: /user/create
  controller: App\Controller\User\CreateUserController

user.edit:
  path: /user/{id}/edit
  controller: App\Controller\User\EditUserController
  requirements:
    id: '\d+'

user.remove.from.struct:
  path: /user/{id}/remove
  controller: App\Controller\User\RemoveFromStructUserController
  requirements:
    id: '\d+'

user.list:
    path: /user/list/{role}
    defaults: { role: all }
    controller: App\Controller\User\ListUserController

#--------USER-PROMOTION--------#

user.promote.decline:
  path: /user/promote/decline/{struct_id}/{user_id}
  controller: App\Controller\User\Promotions\PromoteDeclineController
  requirements:
    id: '\d+'

user.promote.approve:
  path: /user/promote/approve/{struct_id}/{user_id}
  controller: App\Controller\User\Promotions\PromoteApproveController
  requirements:
    id: '\d+'

#--------USER-AJAX--------#

ajax.get.promotion.structs:
  path: /ajax/promotion/{target_user}/structs
  controller: App\Controller\User\Promotions\GetPromotionData

ajax.send.promotion.request:
    path: /ajax/promotion/{struct}/{target_user}
    controller: App\Controller\User\Promotions\SendPromotionRequest

#---------------------------STRUCTS---------------------------#

struct:
  path: /struct/{id}
  controller: App\Controller\Struct\ShowStructController
  requirements:
    id: '\d+'

struct.create:
  path: /struct/create
  controller: App\Controller\Struct\CreateStructController

struct.edit:
  path: /struct/{id}/edit
  controller: App\Controller\Struct\EditStructController
  requirements:
    id: '\d+'

struct.list:
  path: /struct/list/{type}
  defaults: { type: all }
  controller: App\Controller\Struct\ListStructController

#---------------------------SHOP---------------------------#

shop:
  path: /shop
  controller: App\Controller\DefaultController::index

#---------------------------INVITATION-SYSTEM---------------------------#

invite:
  path: /invite
  controller: App\Controller\Invitations\InviteController

#---------------------------EVENTS---------------------------#

events:
  path: /events
  controller: App\Controller\DefaultController::index