name: prod deploy
on:
  push:
    branches:
      - main
jobs:

  pulling:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/scout-database
          git pull origin master
  yarn-install-build:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/scout-database/app
          yarn install
          yarn build
